export const WITHDRAWAL_MESSAGES = [
  "Ill use this ANIME coin to build something on ANIME chain.  Also, Earth domain is best.",
  "Gonna build more with this ANIME coin and not sell it like a degen.",
  "Gonna use this ANIME as my last hope for creating something worthwhile.  God help me."
];

// Updated messages for devFaucet (8 messages for 8 withdrawals) - Match contract exactly
export const DEV_FAUCET_MESSAGES = [
  "Ill use this ANIME coin to test building something on ANIME chain testnet.",
  "Gonna test more with this ANIME testnet coin.",
  "Gonna use this testnet ANIME as fodder to test more c0d3.",
  "This is my fourth to last ANIME amount today, I promise I'll use it wisely.",
  "How much more testnet ANIME do I need?  MOARRRR.",
  "I actually still need more.  I'm probably vibe coding at this point.",
  "I still need more testnet ANIME today...  I likely have bugs in my code if I need this much.",
  "This is the last testnet ANIME I can request today.  Gonna have to make a new wallet."
];

// Original Faucet ABI - Generated by Vyper compiler (Updated with admin functions)
export const FAUCET_ABI = [{"name": "Withdrawal", "inputs": [{"name": "recipient", "type": "address", "indexed": true}, {"name": "amount", "type": "uint256", "indexed": false}, {"name": "timestamp", "type": "uint256", "indexed": false}, {"name": "withdrawal_count", "type": "uint256", "indexed": false}], "anonymous": false, "type": "event"}, {"name": "Deposit", "inputs": [{"name": "sender", "type": "address", "indexed": true}, {"name": "amount", "type": "uint256", "indexed": false}, {"name": "timestamp", "type": "uint256", "indexed": false}], "anonymous": false, "type": "event"}, {"stateMutability": "payable", "type": "fallback"}, {"stateMutability": "payable", "type": "function", "name": "deposit", "inputs": [], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "withdraw", "inputs": [{"name": "_v", "type": "uint8"}, {"name": "_r", "type": "bytes32"}, {"name": "_s", "type": "bytes32"}, {"name": "_message", "type": "string"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "withdrawFor", "inputs": [{"name": "_user", "type": "address"}, {"name": "_v", "type": "uint8"}, {"name": "_r", "type": "bytes32"}, {"name": "_s", "type": "bytes32"}, {"name": "_message", "type": "string"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "addBackend", "inputs": [{"name": "_backend", "type": "address"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "removeBackend", "inputs": [{"name": "_backend", "type": "address"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "transferOwnership", "inputs": [{"name": "_newOwner", "type": "address"}], "outputs": []}, {"stateMutability": "view", "type": "function", "name": "get_balance", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "view", "type": "function", "name": "time_until_next_withdrawal", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "view", "type": "function", "name": "get_nonce", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "view", "type": "function", "name": "get_withdrawal_count", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "view", "type": "function", "name": "get_expected_message", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "string"}]}, {"stateMutability": "nonpayable", "type": "function", "name": "emergencyWithdrawAll", "inputs": [], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "emergencyWithdraw", "inputs": [{"name": "_amount", "type": "uint256"}], "outputs": []}, {"stateMutability": "view", "type": "function", "name": "owner", "inputs": [], "outputs": [{"name": "", "type": "address"}]}, {"stateMutability": "view", "type": "function", "name": "authorizedBackends", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "bool"}]}, {"stateMutability": "view", "type": "function", "name": "last_global_withdrawal", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "view", "type": "function", "name": "last_recipient", "inputs": [], "outputs": [{"name": "", "type": "address"}]}, {"stateMutability": "view", "type": "function", "name": "nonce", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "view", "type": "function", "name": "withdrawal_count", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "nonpayable", "type": "constructor", "inputs": [], "outputs": []}];

// DevFaucet ABI - Generated by Vyper compiler for proof-of-work faucet with 8 daily withdrawals (Updated with admin functions)
export const DEV_FAUCET_ABI = [
  // Events
  {"name": "Withdrawal", "inputs": [{"name": "recipient", "type": "address", "indexed": true}, {"name": "amount", "type": "uint256", "indexed": false}, {"name": "block_time", "type": "uint256", "indexed": false}, {"name": "withdrawal_count", "type": "uint256", "indexed": false}, {"name": "withdrawal_index", "type": "uint256", "indexed": false}, {"name": "difficulty_target", "type": "uint256", "indexed": false}, {"name": "chosen_block", "type": "uint256", "indexed": false}, {"name": "proof_hash", "type": "bytes32", "indexed": false}], "anonymous": false, "type": "event"},
  {"name": "Deposit", "inputs": [{"name": "sender", "type": "address", "indexed": true}, {"name": "amount", "type": "uint256", "indexed": false}, {"name": "block_time", "type": "uint256", "indexed": false}], "anonymous": false, "type": "event"},
  // Admin Events
  {"name": "WithdrawalAmountUpdated", "inputs": [{"name": "index", "type": "uint256", "indexed": false}, {"name": "old_amount", "type": "uint256", "indexed": false}, {"name": "new_amount", "type": "uint256", "indexed": false}, {"name": "updated_by", "type": "address", "indexed": true}], "anonymous": false, "type": "event"},
  {"name": "PowDifficultyUpdated", "inputs": [{"name": "index", "type": "uint256", "indexed": false}, {"name": "old_difficulty", "type": "uint256", "indexed": false}, {"name": "new_difficulty", "type": "uint256", "indexed": false}, {"name": "updated_by", "type": "address", "indexed": true}], "anonymous": false, "type": "event"},
  {"name": "CooldownPeriodUpdated", "inputs": [{"name": "old_period", "type": "uint256", "indexed": false}, {"name": "new_period", "type": "uint256", "indexed": false}, {"name": "updated_by", "type": "address", "indexed": true}], "anonymous": false, "type": "event"},
  {"name": "PowBaseDifficultyUpdated", "inputs": [{"name": "old_base", "type": "uint256", "indexed": false}, {"name": "new_base", "type": "uint256", "indexed": false}, {"name": "updated_by", "type": "address", "indexed": true}], "anonymous": false, "type": "event"},
  {"name": "BaseAmountMultiplierUpdated", "inputs": [{"name": "old_multiplier", "type": "uint256", "indexed": false}, {"name": "new_multiplier", "type": "uint256", "indexed": false}, {"name": "updated_by", "type": "address", "indexed": true}], "anonymous": false, "type": "event"},
  {"name": "BaseDifficultyMultiplierUpdated", "inputs": [{"name": "old_multiplier", "type": "uint256", "indexed": false}, {"name": "new_multiplier", "type": "uint256", "indexed": false}, {"name": "updated_by", "type": "address", "indexed": true}], "anonymous": false, "type": "event"},
  
  // Fallback and basic functions
  {"stateMutability": "payable", "type": "fallback"},
  {"stateMutability": "payable", "type": "function", "name": "deposit", "inputs": [], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "withdraw", "inputs": [{"name": "_chosen_block_hash", "type": "bytes32"}, {"name": "_withdrawal_index", "type": "uint256"}, {"name": "_ip_address", "type": "bytes32"}, {"name": "_nonce", "type": "uint256"}, {"name": "_v", "type": "uint8"}, {"name": "_r", "type": "bytes32"}, {"name": "_s", "type": "bytes32"}], "outputs": []},
  
  // View functions
  {"stateMutability": "view", "type": "function", "name": "get_balance", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "time_until_next_withdrawal", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_nonce", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_withdrawal_count", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_expected_message", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "string"}]},
  {"stateMutability": "view", "type": "function", "name": "get_next_withdrawal_index", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_next_withdrawal_amount", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_difficulty_target", "inputs": [{"name": "_withdrawal_index", "type": "uint256"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "verify_proof_of_work", "inputs": [{"name": "_user", "type": "address"}, {"name": "_chosen_block_hash", "type": "bytes32"}, {"name": "_withdrawal_index", "type": "uint256"}, {"name": "_ip_address", "type": "bytes32"}, {"name": "_nonce", "type": "uint256"}], "outputs": [{"name": "", "type": "bool"}]},
  {"stateMutability": "view", "type": "function", "name": "get_ip_address_hash", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "bytes32"}]},
  {"stateMutability": "view", "type": "function", "name": "get_first_request_time", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_last_successful_block", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "pure", "type": "function", "name": "validate_hash", "inputs": [{"name": "_user", "type": "address"}, {"name": "_chosen_block_hash", "type": "bytes32"}, {"name": "_withdrawal_index", "type": "uint256"}, {"name": "_ip_address", "type": "bytes32"}, {"name": "_nonce", "type": "uint256"}, {"name": "_difficulty_target", "type": "uint256"}], "outputs": [{"name": "", "type": "bool"}]},
  {"stateMutability": "view", "type": "function", "name": "time_until_daily_reset", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "get_user_daily_status", "inputs": [{"name": "_user", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}, {"name": "", "type": "uint256"}, {"name": "", "type": "uint256"}, {"name": "", "type": "uint256"}]},
  
  // Admin functions
  {"stateMutability": "nonpayable", "type": "function", "name": "updateWithdrawalAmount", "inputs": [{"name": "_index", "type": "uint256"}, {"name": "_amount", "type": "uint256"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updateAllWithdrawalAmounts", "inputs": [{"name": "_amounts", "type": "uint256[8]"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updatePowDifficulty", "inputs": [{"name": "_index", "type": "uint256"}, {"name": "_difficulty", "type": "uint256"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updateAllPowDifficulties", "inputs": [{"name": "_difficulties", "type": "uint256[8]"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updateCooldownPeriod", "inputs": [{"name": "_period", "type": "uint256"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updatePowBaseDifficulty", "inputs": [{"name": "_base", "type": "uint256"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updateBaseAmountMultiplier", "inputs": [{"name": "_multiplier", "type": "uint256"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "updateBaseDifficultyMultiplier", "inputs": [{"name": "_multiplier", "type": "uint256"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "transferOwnership", "inputs": [{"name": "_newOwner", "type": "address"}], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "emergencyWithdrawAll", "inputs": [], "outputs": []},
  {"stateMutability": "nonpayable", "type": "function", "name": "emergencyWithdraw", "inputs": [{"name": "_amount", "type": "uint256"}], "outputs": []},
  
  // State variables (view)
  {"stateMutability": "view", "type": "function", "name": "owner", "inputs": [], "outputs": [{"name": "", "type": "address"}]},
  {"stateMutability": "view", "type": "function", "name": "cooldown_period", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "pow_base_difficulty", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "base_amount_multiplier", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "base_difficulty_multiplier", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "withdrawal_amounts", "inputs": [{"name": "arg0", "type": "uint256"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "pow_difficulty_targets", "inputs": [{"name": "arg0", "type": "uint256"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "last_global_withdrawal", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "nonce", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "withdrawal_count", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "first_request_time", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  {"stateMutability": "view", "type": "function", "name": "ip_address_hash", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "bytes32"}]},
  {"stateMutability": "view", "type": "function", "name": "last_successful_block", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}]},
  
  // Constructor
  {"stateMutability": "nonpayable", "type": "constructor", "inputs": [], "outputs": []}
];

// Original FaucetServer ABI - Generated by Vyper compiler
export const FAUCET_SERVER_ABI = [{"stateMutability": "payable", "type": "function", "name": "deposit", "inputs": [], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "requestWithdrawal", "inputs": [{"name": "_faucet", "type": "address"}, {"name": "_user", "type": "address"}, {"name": "_v", "type": "uint8"}, {"name": "_r", "type": "bytes32"}, {"name": "_s", "type": "bytes32"}, {"name": "_message", "type": "string"}], "outputs": []}, {"stateMutability": "view", "type": "function", "name": "owner", "inputs": [], "outputs": [{"name": "", "type": "address"}]}, {"stateMutability": "nonpayable", "type": "constructor", "inputs": [], "outputs": []}];

// DevFaucetServer ABI - Generated by Vyper compiler for proof-of-work server withdrawals
export const DEV_FAUCET_SERVER_ABI = [{"stateMutability": "payable", "type": "function", "name": "deposit", "inputs": [], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "requestWithdrawal", "inputs": [{"name": "_faucet", "type": "address"}, {"name": "_chosen_block_hash", "type": "bytes32"}, {"name": "_withdrawal_index", "type": "uint256"}, {"name": "_ip_address", "type": "bytes32"}, {"name": "_nonce", "type": "uint256"}, {"name": "_v", "type": "uint8"}, {"name": "_r", "type": "bytes32"}, {"name": "_s", "type": "bytes32"}], "outputs": []}, {"stateMutability": "view", "type": "function", "name": "get_balance", "inputs": [], "outputs": [{"name": "", "type": "uint256"}]}, {"stateMutability": "nonpayable", "type": "function", "name": "withdraw_native", "inputs": [{"name": "_amount", "type": "uint256"}], "outputs": []}, {"stateMutability": "nonpayable", "type": "function", "name": "transfer_ownership", "inputs": [{"name": "_new_owner", "type": "address"}], "outputs": []}, {"stateMutability": "view", "type": "function", "name": "owner", "inputs": [], "outputs": [{"name": "", "type": "address"}]}, {"stateMutability": "nonpayable", "type": "constructor", "inputs": [], "outputs": []}];

export const NETWORKS = {
  animechain: {
    chainId: '0x10D88', // 69000 in hex
    chainName: 'AnimeChain',
    nativeCurrency: {
      name: 'Anime',
      symbol: 'ANIME',
      decimals: 18
    },
    rpcUrls: ['https://rpc-animechain-39xf6m45e3.t.conduit.xyz/'],
    blockExplorerUrls: ['https://explorer-animechain-39xf6m45e3.t.conduit.xyz/'],
    iconUrls: [window.location.origin + '/assets/animecoin.png']
  },
  animechain_testnet: {
    chainId: '0x1AF4', // 6900 in hex
    chainName: 'AnimeChain Testnet',
    nativeCurrency: {
      name: 'Test Anime',
      symbol: 'tANIME',
      decimals: 18
    },
    rpcUrls: ['https://testnet-rpc.anime.xyz/'], // Conduit testnet RPC
    blockExplorerUrls: ['https://explorer-animechain-testnet-i8yja6a1a0.t.conduit.xyz/'], // Conduit testnet explorer
    iconUrls: [window.location.origin + '/assets/animecoin.png'],
    // Testnet configuration details
    parentChainId: 421614, // Arbitrum Sepolia
    nativeTokenAddress: '0x38208F36E9d6CE86ccE0977fA5690140Ec78A5d4',
    // Core contracts
    coreContracts: {
      rollup: '0xb31ae2dA8AF1227D3533DBE11a5E9B0bCfc738B4',
      inbox: '0x0590A4DEDCE7145e81BF59DB39029a27A6783141',
      outbox: '0xb1C0EbEADFf5f277727ABf8aCdC1031AA119A26d',
      bridge: '0x554105BbC8eB136933B210Eb60b5d7C9c592d6D8',
      sequencerInbox: '0x742FFc80b224C815E8faeE34DC0d612c722d5Bd0'
    },
    // Token bridge contracts
    tokenBridge: {
      l2: {
        router: '0xD9d44147aBefa4a965dfA02792A49A8672e1464F',
        standardGateway: '0xfD99AFa35cFb778cB6d16552CE62874E2838a293',
        customGateway: '0x7aE1625b7284dFcb6CA1431a547c4eA80b0A0490',
        multicall: '0xce1CAd780c529e66e3aa6D952a1ED9A6447791c1'
      },
      l3: {
        router: '0xbEE16d3e349DD7A5aEC190b1C03aA8f65A915360',
        standardGateway: '0x14B739e95cABeEC8C9f550530C5F701CBaAe9D38',
        customGateway: '0xEC44a2AcE1a58f5520Ca716873dF6E3f39c498b0',
        multicall: '0x2217BF4E11F8bd17A10e29F14E7d0E99A287E88F'
      }
    }
  },
  testnet: {
    chainId: '0x1AF4', // 6900 in hex
    chainName: 'AnimeChain Testnet',
    nativeCurrency: {
      name: 'Test Anime',
      symbol: 'tANIME',
      decimals: 18
    },
    rpcUrls: ['https://testnet-rpc.anime.xyz/'],
    blockExplorerUrls: ['https://explorer-animechain-testnet-i8yja6a1a0.t.conduit.xyz/'],
    iconUrls: [window.location.origin + '/assets/animecoin.png']
  }
}; 